const PDFDocument = require('pdfkit-table');
const db = require('../db');

const reportService = {
    /**
     * Generate Meeting Minutes PDF
     */
    generateMeetingMinutes: async (sessionId) => {
        return new Promise((resolve, reject) => {
            // 1. Fetch Session Data
            db.get(`
                SELECT s.*, g.name as groupName 
                FROM meeting_sessions s
                JOIN groups g ON s.groupId = g.id
                WHERE s.id = ?
            `, [sessionId], (err, session) => {
                if (err || !session) return reject(err || new Error('Session not found'));

                // 2. Fetch Transactions for this session
                db.all(`
                    SELECT t.*, m.name as memberName 
                    FROM transactions t
                    JOIN members m ON t.memberId = m.id
                    WHERE t.sessionId = ?
                `, [sessionId], async (err, transactions) => {
                    if (err) return reject(err);

                    try {
                        const doc = new PDFDocument({ margin: 30, size: 'A4' });
                        let buffers = [];
                        doc.on('data', buffers.push.bind(buffers));
                        doc.on('end', () => {
                            let pdfData = Buffer.concat(buffers);
                            resolve(pdfData);
                        });

                        // --- HEADER ---
                        doc.fontSize(20).text('UKOMBOZI TBMS', { align: 'center' });
                        doc.fontSize(14).text('OFFICIAL MEETING MINUTES', { align: 'center' });
                        doc.moveDown();
                        doc.strokeColor('#eeeeee').moveTo(30, doc.y).lineTo(565, doc.y).stroke();
                        doc.moveDown();

                        // --- MEETING INFO ---
                        doc.fontSize(10).font('Helvetica-Bold').text('Group: ', { continued: true }).font('Helvetica').text(session.groupName);
                        doc.font('Helvetica-Bold').text('Date: ', { continued: true }).font('Helvetica').text(new Date(session.date).toLocaleDateString());
                        doc.font('Helvetica-Bold').text('Status: ', { continued: true }).font('Helvetica').text(session.status);
                        doc.moveDown();

                        // --- TOTALS SUMMARY ---
                        const totals = session.totals ? JSON.parse(session.totals) : {
                            savings: 0, stl_repayment: 0, ltl_repayment: 0, loan_interest: 0, welfare: 0, fines: 0, loans_issued: 0
                        };

                        const summaryTable = {
                            title: "Financial Summary",
                            headers: ["Category", "Total (KES)"],
                            rows: [
                                ["Total Savings", totals.savings.toLocaleString()],
                                ["STL Repayments", totals.stl_repayment.toLocaleString()],
                                ["LTL Repayments", totals.ltl_repayment.toLocaleString()],
                                ["Loan Interest", totals.loan_interest.toLocaleString()],
                                ["Welfare Contribution", totals.welfare.toLocaleString()],
                                ["Fines & Penalties", totals.fines.toLocaleString()],
                                ["New Loans Issued", totals.loans_issued.toLocaleString()],
                            ]
                        };
                        await doc.table(summaryTable, { width: 300 });

                        doc.addPage();

                        // --- DETAILED TRANSACTIONS ---
                        const txRows = transactions.map(t => [
                            t.memberName,
                            t.attended ? "Yes" : "No",
                            t.savings_amount.toLocaleString(),
                            t.stl_repayment.toLocaleString(),
                            t.ltl_repayment.toLocaleString(),
                            t.loans_issued.toLocaleString()
                        ]);

                        const detailTable = {
                            title: "Detailed Member Transactions",
                            headers: ["Member", "Attended", "Savings", "STL Repay", "LTL Repay", "Loan Issued"],
                            rows: txRows
                        };
                        await doc.table(detailTable, {
                            prepareHeader: () => doc.font("Helvetica-Bold").fontSize(8),
                            prepareRow: () => doc.font("Helvetica").fontSize(8)
                        });

                        // --- FOOTER ---
                        doc.moveDown();
                        doc.fontSize(10).text('Generated by Ukombozi Local System', { align: 'center', oblique: true });
                        doc.text(`Timestamp: ${new Date().toLocaleString()}`, { align: 'center' });

                        doc.end();
                    } catch (e) {
                        reject(e);
                    }
                });
            });
        });
    },

    /**
     * Generate Member Statement PDF
     */
    generateMemberStatement: async (memberId, startDate, endDate) => {
        return new Promise((resolve, reject) => {
            // 1. Fetch Member Details
            db.get(`
                SELECT m.*, g.name as groupName 
                FROM members m
                JOIN groups g ON m.group_id = g.id
                WHERE m.id = ?
            `, [memberId], (err, member) => {
                if (err || !member) return reject(err || new Error('Member not found'));

                // 2. Fetch history with optional filtering
                let query = `
                    SELECT t.*, s.date as sessionDate 
                    FROM transactions t
                    LEFT JOIN meeting_sessions s ON t.sessionId = s.id
                    WHERE t.memberId = ?
                `;
                const params = [memberId];

                if (startDate) {
                    query += ` AND (s.date >= ? OR (s.date IS NULL AND t.created_at >= ?))`;
                    params.push(startDate, startDate);
                }
                if (endDate) {
                    query += ` AND (s.date <= ? OR (s.date IS NULL AND t.created_at <= ?))`;
                    params.push(endDate, endDate);
                }

                query += ` ORDER BY t.created_at DESC`;

                db.all(query, params, async (err, history) => {
                    if (err) return reject(err);

                    try {
                        const doc = new PDFDocument({ margin: 30, size: 'A4' });
                        let buffers = [];
                        doc.on('data', buffers.push.bind(buffers));
                        doc.on('end', () => {
                            let pdfData = Buffer.concat(buffers);
                            resolve(pdfData);
                        });

                        // --- HEADER ---
                        doc.fontSize(20).text('UKOMBOZI TBMS', { align: 'center' });
                        doc.fontSize(14).text('MEMBER ACCOUNT STATEMENT', { align: 'center' });
                        doc.moveDown();

                        // --- MEMBER INFO ---
                        doc.fontSize(10).font('Helvetica-Bold').text('Member Name: ', { continued: true }).font('Helvetica').text(member.name);
                        doc.font('Helvetica-Bold').text('Phone: ', { continued: true }).font('Helvetica').text(member.phone);
                        doc.font('Helvetica-Bold').text('Group: ', { continued: true }).font('Helvetica').text(member.groupName);
                        doc.moveDown();

                        // --- BALANCES ---
                        const balanceTable = {
                            title: "Current Balances",
                            headers: ["Asset Type", "Amount (KES)"],
                            rows: [
                                ["Total Savings", member.current_savings.toLocaleString()],
                                ["Active Loan Balance", member.active_loan_balance.toLocaleString()]
                            ]
                        };
                        await doc.table(balanceTable, { width: 300 });

                        doc.moveDown();

                        // --- HISTORY ---
                        const histRows = history.map(h => [
                            h.sessionDate ? new Date(h.sessionDate).toLocaleDateString() : new Date(h.created_at).toLocaleDateString(),
                            h.savings_amount.toLocaleString(),
                            (h.stl_repayment + h.ltl_repayment).toLocaleString(),
                            h.loans_issued.toLocaleString(),
                            h.transaction_type || 'Meeting'
                        ]);

                        const historyTable = {
                            title: "Recent Transaction History",
                            headers: ["Date", "Savings", "Repayments", "Loans Issued", "Description"],
                            rows: histRows
                        };
                        await doc.table(historyTable, {
                            prepareHeader: () => doc.font("Helvetica-Bold").fontSize(8),
                            prepareRow: () => doc.font("Helvetica").fontSize(8)
                        });

                        doc.end();
                    } catch (e) {
                        reject(e);
                    }
                });
            });
        });
    },

    /**
     * Generate Dividend Report PDF
     */
    generateDividendReport: async (runId) => {
        return new Promise((resolve, reject) => {
            // 1. Fetch Run Data
            db.get(`
                SELECT r.*, g.name as groupName 
                FROM dividend_runs r
                JOIN groups g ON r.group_id = g.id
                WHERE r.id = ?
            `, [runId], (err, run) => {
                if (err || !run) return reject(err || new Error('Dividend run not found'));

                // 2. Mock Allocations (since we don't have a table for them yet in this local version)
                // In a full system, we'd query a dividend_allocations table
                const allocations = [
                    { member_name: 'Alice Wanjiku', average_shares: 5000, gross_dividend: 600, net_dividend: 600 },
                    { member_name: 'John Doe', average_shares: 3000, gross_dividend: 360, net_dividend: 360 },
                    { member_name: 'Hilda Sigei', average_shares: 12000, gross_dividend: 1440, net_dividend: 1440 }
                ];

                try {
                    const doc = new PDFDocument({ margin: 30, size: 'A4', layout: 'landscape' });
                    let buffers = [];
                    doc.on('data', buffers.push.bind(buffers));
                    doc.on('end', () => {
                        let pdfData = Buffer.concat(buffers);
                        resolve(pdfData);
                    });

                    // --- HEADER ---
                    doc.fontSize(20).text('UKOMBOZI TBMS', { align: 'center' });
                    doc.fontSize(14).text(`DIVIDEND DISTRIBUTION REPORT - FY ${run.financial_year}`, { align: 'center' });
                    doc.fontSize(12).text(run.groupName, { align: 'center' });
                    doc.moveDown();
                    doc.strokeColor('#eeeeee').moveTo(30, doc.y).lineTo(doc.page.width - 30, doc.y).stroke();
                    doc.moveDown();

                    // --- FINANCIAL SUMMARY ---
                    const summaryTable = {
                        title: "Executive Summary",
                        headers: ["Metric", "Value (KES)"],
                        rows: [
                            ["Total Income", (run.banking_interest + run.stl_interest + run.ltl_interest + run.penalties + run.other_income).toLocaleString()],
                            ["Operating Expenses", run.operating_expenses.toLocaleString()],
                            ["TRF Deductions", (run.mandatory_reserves + run.risk_buffer + run.reinvested_capital).toLocaleString()],
                            ["Allocable Profit", run.allocable_profit.toLocaleString()],
                            ["Distribution Rate", `${(run.profit_share_percentage)}%`],
                            ["Dividend Rate", `${(run.dividend_rate * 100).toFixed(2)}%`]
                        ]
                    };
                    doc.table(summaryTable, { width: 400 });

                    doc.addPage();

                    // --- ALLOCATIONS ---
                    const allocRows = allocations.map(a => [
                        a.member_name,
                        a.average_shares.toLocaleString(),
                        a.gross_dividend.toLocaleString(),
                        "0", // Arrears
                        a.net_dividend.toLocaleString()
                    ]);

                    const detailTable = {
                        title: "Member Dividend Allocations",
                        headers: ["Member", "Avg Shares", "Gross Div", "Arrears Offset", "Net Payout"],
                        rows: allocRows
                    };
                    doc.table(detailTable, {
                        prepareHeader: () => doc.font("Helvetica-Bold").fontSize(10),
                        prepareRow: () => doc.font("Helvetica").fontSize(9)
                    });

                    // --- FOOTER ---
                    doc.moveDown();
                    doc.fontSize(10).text('Approved for Distribution by Group Committee', { align: 'center' });
                    doc.text(`Report ID: ${run.run_number} | Generated: ${new Date().toLocaleString()}`, { align: 'center', oblique: true });

                    doc.end();
                } catch (e) {
                    reject(e);
                }
            });
        });
    },

    /**
     * Generate Contribution Compliance Report PDF
     */
    generateContributionComplianceReport: async (month, groupId) => {
        return new Promise((resolve, reject) => {
            // Mock Data for now - in production would query DB
            const data = [
                { name: 'Alice Wanjiku', status: 'Paid', amount: 2000, expected: 2000 },
                { name: 'John Doe', status: 'Partial', amount: 1500, expected: 2000 },
                { name: 'Hilda Sigei', status: 'Skipped', amount: 0, expected: 2000 }
            ];

            try {
                const doc = new PDFDocument({ margin: 30, size: 'A4' });
                let buffers = [];
                doc.on('data', buffers.push.bind(buffers));
                doc.on('end', () => resolve(Buffer.concat(buffers)));

                doc.fontSize(20).text('UKOMBOZI TBMS', { align: 'center' });
                doc.fontSize(14).text(`CONTRIBUTION COMPLIANCE REPORT - ${month}`, { align: 'center' });
                doc.moveDown();

                const rows = data.map(d => [d.name, d.status, d.amount.toLocaleString(), d.expected.toLocaleString()]);
                const table = {
                    title: "Compliance Status",
                    headers: ["Member", "Status", "Paid", "Expected"],
                    rows: rows
                };
                doc.table(table);
                doc.end();
            } catch (e) {
                reject(e);
            }
        });
    },

    /**
     * Generate Loan Repayment Report PDF
     */
    generateLoanRepaymentReport: async (month, groupId, type) => {
        return new Promise((resolve, reject) => {
            // Mock Data
            const data = [
                { name: 'Alice Wanjiku', loanType: 'LTL', paid: 5000, expected: 5000, balance: 45000 },
                { name: 'John Doe', loanType: 'STL', paid: 1000, expected: 2500, balance: 12000 }
            ];

            try {
                const doc = new PDFDocument({ margin: 30, size: 'A4' });
                let buffers = [];
                doc.on('data', buffers.push.bind(buffers));
                doc.on('end', () => resolve(Buffer.concat(buffers)));

                doc.fontSize(20).text('UKOMBOZI TBMS', { align: 'center' });
                doc.fontSize(14).text(`LOAN REPAYMENT REPORT - ${month}`, { align: 'center' });
                doc.moveDown();

                const rows = data.map(d => [d.name, d.loanType, d.paid.toLocaleString(), d.expected.toLocaleString(), d.balance.toLocaleString()]);
                const table = {
                    title: "Repayment Details",
                    headers: ["Member", "Type", "Paid", "Expected", "Balance"],
                    rows: rows
                };
                doc.table(table);
                doc.end();
            } catch (e) {
                reject(e);
            }
        });
    }
    ,

    /**
     * Generate Partnership Statement (Group vs Company)
     */
    generatePartnershipStatement: async (groupId) => {
        return new Promise((resolve, reject) => {
            // 1. Fetch Group & Financials
            db.get("SELECT name FROM groups WHERE id = ?", [groupId], (err, group) => {
                if (err || !group) return reject("Group not found");

                // 2. Fetch Aggregates
                const queries = {
                    savings: "SELECT SUM(current_savings) as val FROM members WHERE group_id = ?",
                    commitments: "SELECT SUM(amount) as val FROM group_commitments WHERE group_id = ? AND status = 'LOCKED'",
                    topups: "SELECT SUM(amount) as val FROM company_investments WHERE group_id = ? AND status = 'ACTIVE'",
                    products: "SELECT SUM(financed_amount) as val FROM product_financing pf JOIN members m ON pf.member_id = m.id WHERE m.group_id = ? AND pf.status = 'ACTIVE'"
                };

                // Run parallel queries (manual promise style for sqlite3)
                const runQ = (q) => new Promise((res, rej) => db.get(q, [groupId], (e, r) => e ? rej(e) : res(r?.val || 0)));

                Promise.all([
                    runQ(queries.savings),
                    runQ(queries.commitments),
                    runQ(queries.topups),
                    runQ(queries.products)
                ]).then(([savings, commitments, topups, products]) => {
                    const doc = new PDFDocument({ margin: 40, size: 'A4' });
                    let buffers = [];
                    doc.on('data', buffers.push.bind(buffers));
                    doc.on('end', () => resolve(Buffer.concat(buffers)));

                    // BRANDING
                    doc.fontSize(24).fillColor('#008524').text('UKOMBOZI', { align: 'center' }).fillColor('black');
                    doc.fontSize(10).text('PARTNERSHIP STATEMENT', { align: 'center', letterSpacing: 2 });
                    doc.moveDown();

                    // INFO
                    doc.fontSize(12).font('Helvetica-Bold').text(`Partner Group: ${group.name}`);
                    doc.font('Helvetica').text(`Date: ${new Date().toLocaleDateString()}`);
                    doc.moveDown();

                    // 2-COLUMN LAYOUT
                    const mid = doc.page.width / 2;
                    const yStart = doc.y;

                    // LEFT: GROUP POSITION
                    doc.rect(40, yStart, mid - 50, 200).fillOpacity(0.05).fill('#008524').stroke('#008524').fillOpacity(1);
                    doc.fillColor('#006400').fontSize(14).font('Helvetica-Bold').text('GROUP FUNDS', 50, yStart + 20);
                    doc.fontSize(10).font('Helvetica').text('Member Savings:', 50, yStart + 50);
                    doc.font('Helvetica-Bold').text(`KES ${savings.toLocaleString()}`, 150, yStart + 50);

                    doc.font('Helvetica').text('Commitment Deposit:', 50, yStart + 80);
                    doc.font('Helvetica-Bold').text(`KES ${commitments.toLocaleString()}`, 150, yStart + 80);

                    doc.moveTo(50, yStart + 110).lineTo(mid - 20, yStart + 110).stroke();
                    doc.fontSize(12).text('TOTAL SECURITY', 50, yStart + 120);
                    doc.fontSize(14).text(`KES ${(savings + commitments).toLocaleString()}`, 50, yStart + 135);


                    // RIGHT: COMPANY POSITION
                    doc.rect(mid + 10, yStart, mid - 50, 200).fillOpacity(0.05).fill('#00008B').stroke('#00008B').fillOpacity(1);
                    doc.fillColor('#00008B').fontSize(14).font('Helvetica-Bold').text('COMPANY FUNDS', mid + 20, yStart + 20);

                    doc.fontSize(10).font('Helvetica').text('Capital Top-Ups:', mid + 20, yStart + 50);
                    doc.font('Helvetica-Bold').text(`KES ${topups.toLocaleString()}`, mid + 120, yStart + 50);

                    doc.font('Helvetica').text('Product Financing:', mid + 20, yStart + 80);
                    doc.font('Helvetica-Bold').text(`KES ${products.toLocaleString()}`, mid + 120, yStart + 80);

                    doc.moveTo(mid + 20, yStart + 110).lineTo(doc.page.width - 40, yStart + 110).stroke();
                    doc.fontSize(12).text('TOTAL EXPOSURE', mid + 20, yStart + 120);
                    doc.fontSize(14).text(`KES ${(topups + products).toLocaleString()}`, mid + 20, yStart + 135);

                    // NET POSITION
                    doc.moveDown(8);
                    const net = (topups + products) - (savings + commitments);
                    const msg = net > 0 ? "Net Company Risk (Uncovered)" : "Fully Secured (Surplus)";
                    const color = net > 0 ? 'red' : 'green';

                    doc.fontSize(16).fillColor(color).text(`${msg}: KES ${Math.abs(net).toLocaleString()}`, { align: 'center' });

                    // Footer
                    doc.fontSize(8).fillColor('gray').text('This statement confirms the mutual partnership standing.', 40, 750, { align: 'center' });

                    doc.end();

                }).catch(reject);
            });
        });
    }
};

module.exports = reportService;
