import jsPDF from 'jspdf';
import 'jspdf-autotable';

class PDFReportService {
    constructor() {
        this.companyName = "UKOMBOZINI";
        this.companyTagline = "Treasury & Business Management System";
        this.brandColor = [46, 125, 50]; // Safaricom Green (approx)
        this.secondaryColor = [22, 163, 74];
    }

    // Helper: Add Header
    _addHeader(doc, title, subtitle) {
        const pageWidth = doc.internal.pageSize.width;

        // Brand Bar
        doc.setFillColor(...this.brandColor);
        doc.rect(0, 0, pageWidth, 20, 'F');

        // Company Name
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text(this.companyName, 14, 13);

        // Tagline
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(this.companyTagline, 14, 18);

        // Title
        doc.setTextColor(40, 40, 40);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(title, 14, 35);

        // Subtitle/Meta
        if (subtitle) {
            doc.setFontSize(10);
            doc.setTextColor(100, 100, 100);
            doc.setFont('helvetica', 'normal');
            doc.text(subtitle, 14, 42);
        }

        // Divider
        doc.setDrawColor(200, 200, 200);
        doc.line(14, 48, pageWidth - 14, 48);
    }

    // Helper: Add Footer
    _addFooter(doc) {
        const pageCount = doc.internal.getNumberOfPages();
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;

        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);

            const timestamp = new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });
            doc.text(`Generated by UKOMBOZINI | ${timestamp}`, 14, pageHeight - 10);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth - 25, pageHeight - 10);
        }
    }

    /**
     * Generate Loan Repayment Schedule PDF
     * @param {Object} loanDetails - { id, member_name, amount, duration, start_date }
     * @param {Array} schedule - Array of schedule objects
     */
    generateLoanSchedule(loanDetails, schedule) {
        const doc = new jsPDF();
        const loanId = loanDetails.id || 'N/A';

        this._addHeader(doc, 'Loan Repayment Schedule', `Loan ID: ${loanId} | Member: ${loanDetails.member_name}`);

        // Loan Summary Box
        doc.setFillColor(245, 247, 250);
        doc.roundedRect(14, 55, 180, 25, 3, 3, 'F');

        doc.setFontSize(10);
        doc.setTextColor(80, 80, 80);

        doc.setFont('helvetica', 'bold');
        doc.text('Principal Amount:', 20, 65);
        doc.setFont('helvetica', 'normal');
        doc.text(`KES ${parseFloat(loanDetails.amount || 0).toLocaleString()}`, 60, 65);

        doc.setFont('helvetica', 'bold');
        doc.text('Duration:', 20, 72);
        doc.setFont('helvetica', 'normal');
        doc.text(`${loanDetails.duration || 0} Months`, 60, 72);

        doc.setFont('helvetica', 'bold');
        doc.text('Start Date:', 100, 65);
        doc.setFont('helvetica', 'normal');
        doc.text(loanDetails.start_date || 'N/A', 130, 65);

        doc.setFont('helvetica', 'bold');
        doc.text('Interest Rate:', 100, 72);
        doc.setFont('helvetica', 'normal');
        doc.text(`${loanDetails.interest_rate || 0}%`, 130, 72);


        // Table
        const tableColumn = ["Inst #", "Due Date", "Expected", "Principal", "Interest", "Shares", "Status"];
        const tableRows = [];

        schedule.forEach(row => {
            const rowData = [
                row.installment_number,
                new Date(row.due_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }),
                `KES ${row.expected_installment?.toLocaleString()}`,
                `KES ${row.expected_principal?.toLocaleString()}`,
                `KES ${row.expected_interest?.toLocaleString()}`,
                `KES ${row.expected_shares?.toLocaleString()}`,
                row.status?.toUpperCase() || 'PENDING'
            ];
            tableRows.push(rowData);
        });

        doc.autoTable({
            head: [tableColumn],
            body: tableRows,
            startY: 85,
            theme: 'grid',
            headStyles: {
                fillColor: this.brandColor,
                textColor: [255, 255, 255],
                fontStyle: 'bold'
            },
            alternateRowStyles: { fillColor: [240, 253, 244] },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 15 }, // Inst #
                6: { fontStyle: 'bold' } // Status
            },
            didParseCell: function (data) {
                if (data.section === 'body' && data.column.index === 6) {
                    const status = data.cell.raw;
                    if (status === 'PAID') data.cell.styles.textColor = [22, 163, 74];
                    if (status === 'OVERDUE') data.cell.styles.textColor = [220, 38, 38];
                    if (status === 'PENDING') data.cell.styles.textColor = [202, 138, 4];
                }
            }
        });

        this._addFooter(doc);
        doc.save(`Loan_Schedule_${loanId}.pdf`);
    }

    /**
     * Generate Member Statement PDF
     * @param {Object} member - { name, id, phone, groupName }
     * @param {Array} transactions - Array of transaction objects
     * @param {Object} summary - { totalSavings, activeLoans, arrears }
     */
    generateMemberStatement(member, transactions, summary) {
        const doc = new jsPDF();
        const dateRange = `Generated on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`;

        this._addHeader(doc, 'Member Account Statement', `${member.name} | ${member.groupName || 'No Group'} | ${dateRange}`);

        // Summary Cards
        const startY = 55;
        const boxWidth = 55;
        const spacing = 10;

        // Savings Box
        doc.setFillColor(240, 253, 244); // Light Green
        doc.setDrawColor(22, 163, 74);
        doc.roundedRect(14, startY, boxWidth, 25, 2, 2, 'FD');
        doc.setFontSize(9);
        doc.setTextColor(22, 163, 74);
        doc.text('TOTAL SAVINGS', 19, startY + 8);
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'bold');
        doc.text(`KES ${summary.totalSavings?.toLocaleString()}`, 19, startY + 18);

        // Loans Box
        doc.setFillColor(239, 246, 255); // Light Blue
        doc.setDrawColor(37, 99, 235);
        doc.roundedRect(14 + boxWidth + spacing, startY, boxWidth, 25, 2, 2, 'FD');
        doc.setFontSize(9);
        doc.setTextColor(37, 99, 235);
        doc.setFont('helvetica', 'normal');
        doc.text('ACTIVE LOANS', 19 + boxWidth + spacing, startY + 8);
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'bold');
        doc.text(`KES ${summary.activeLoans?.toLocaleString()}`, 19 + boxWidth + spacing, startY + 18);

        // Net Position Box
        const netPos = (summary.totalSavings || 0) - (summary.activeLoans || 0);
        doc.setFillColor(255, 251, 235); // Light Amber
        doc.setDrawColor(217, 119, 6);
        doc.roundedRect(14 + (boxWidth + spacing) * 2, startY, boxWidth, 25, 2, 2, 'FD');
        doc.setFontSize(9);
        doc.setTextColor(217, 119, 6);
        doc.setFont('helvetica', 'normal');
        doc.text('NET POSITION', 19 + (boxWidth + spacing) * 2, startY + 8);
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'bold');
        doc.text(`KES ${netPos.toLocaleString()}`, 19 + (boxWidth + spacing) * 2, startY + 18);


        // Transactions Table
        const tableColumn = ["Date", "Ref", "Type", "Description", "Amount (KES)", "Balance"];
        const tableRows = [];

        transactions.forEach(tx => {
            const amount = parseFloat(tx.amount || 0);
            const isCredit = ['SAVINGS_DEPOSIT', 'LOAN_REPAYMENT', 'WELFARE_CONTRIBUTION'].includes(tx.transaction_type);

            // Format amounts (Cr/Dr logic visual only)
            const amountStr = `${isCredit ? '+' : '-'} ${Math.abs(amount).toLocaleString()}`;

            const rowData = [
                new Date(tx.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
                tx.reference || '-',
                tx.transaction_type?.replace(/_/g, ' '),
                tx.description || '-',
                amountStr,
                // Balance column is tricky without running balance logic, leaving typically blank or accumulative if available
                tx.running_balance ? `KES ${tx.running_balance.toLocaleString()}` : '-'
            ];
            tableRows.push(rowData);
        });

        doc.autoTable({
            head: [tableColumn],
            body: tableRows,
            startY: startY + 35,
            theme: 'striped',
            headStyles: {
                fillColor: [55, 65, 81],
                textColor: 255
            },
            styles: { fontSize: 8 },
            columnStyles: {
                4: { halign: 'right', fontStyle: 'bold' },
                5: { halign: 'right' }
            },
            didParseCell: function (data) {
                if (data.section === 'body' && data.column.index === 4) {
                    // Color code amounts
                    const text = data.cell.raw;
                    if (text.startsWith('+')) data.cell.styles.textColor = [22, 163, 74];
                    else data.cell.styles.textColor = [220, 38, 38];
                }
            }
        });

        this._addFooter(doc);
        doc.save(`Statement_${member.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
    }
}

export const pdfReportService = new PDFReportService();
export default pdfReportService;
