import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Generate a professional Member Statement PDF
 * This creates a bank-grade statement suitable for audits, disputes, and member records
 */
export const generateMemberStatementPDF = (member, transactions, period = 'All Time') => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 20;

    // ===== HEADER =====
    // Organization branding
    doc.setFillColor(0, 87, 61); // Safaricom Green
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('UKOMBOZI TABLE BANKING SYSTEM', pageWidth / 2, 15, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Official Member Statement', pageWidth / 2, 25, { align: 'center' });

    doc.setFontSize(8);
    doc.text('System-Generated Document - Read Only', pageWidth / 2, 32, { align: 'center' });

    // Reset text color
    doc.setTextColor(0, 0, 0);
    yPos = 50;

    // ===== MEMBER INFORMATION =====
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('MEMBER INFORMATION', 14, yPos);
    yPos += 2;

    // Info box
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.rect(14, yPos, pageWidth - 28, 32);
    yPos += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Member Name:', 18, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(member.name || 'N/A', 50, yPos);

    doc.setFont('helvetica', 'bold');
    doc.text('Phone:', 120, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(member.phone || 'N/A', 140, yPos);
    yPos += 6;

    doc.setFont('helvetica', 'bold');
    doc.text('Group:', 18, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(member.groupName || 'N/A', 50, yPos);

    doc.setFont('helvetica', 'bold');
    doc.text('Statement Period:', 120, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(period, 160, yPos);
    yPos += 6;

    doc.setFont('helvetica', 'bold');
    doc.text('Generated On:', 18, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    }), 50, yPos);

    doc.setFont('helvetica', 'bold');
    doc.text('Generated By:', 120, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text('System (Auto)', 160, yPos);

    yPos += 12;

    // ===== FINANCIAL SUMMARY =====
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('FINANCIAL SUMMARY', 14, yPos);
    yPos += 2;

    const netPosition = member.savings - (member.activeLoans + member.arrears);

    // Financial summary table
    doc.autoTable({
        startY: yPos,
        head: [['Category', 'Amount (KES)']],
        body: [
            ['Total Savings', `KES ${member.savings.toLocaleString()}`],
            ['Total Shares', `KES ${(member.shares || 5000).toLocaleString()}`],
            ['Total Loans Disbursed', `KES ${(member.totalLoansReceived || member.activeLoans).toLocaleString()}`],
            ['Total Loan Repaid', `KES ${(member.totalRepaid || 0).toLocaleString()}`],
            ['Outstanding Loan Balance', `KES ${member.activeLoans.toLocaleString()}`],
            ['Current Arrears', `KES ${member.arrears.toLocaleString()}`],
            [{
                content: 'Net Position',
                styles: { fontStyle: 'bold', fillColor: [240, 240, 240] }
            }, {
                content: `KES ${netPosition.toLocaleString()}`,
                styles: {
                    fontStyle: 'bold',
                    textColor: netPosition >= 0 ? [0, 128, 0] : [255, 0, 0],
                    fillColor: [240, 240, 240]
                }
            }]
        ],
        theme: 'grid',
        headStyles: { fillColor: [0, 87, 61], textColor: [255, 255, 255], fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 3 },
        columnStyles: {
            0: { fontStyle: 'bold' },
            1: { halign: 'right', fontStyle: 'bold' }
        }
    });

    yPos = doc.lastAutoTable.finalY + 10;

    // ===== DETAILED STATEMENT TABLE =====
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('DETAILED STATEMENT', 14, yPos);
    yPos += 2;

    // Prepare transaction data
    const tableData = transactions.map(txn => [
        new Date(txn.date).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }),
        txn.type,
        txn.debit > 0 ? `KES ${txn.debit.toLocaleString()}` : '–',
        txn.credit > 0 ? `KES ${txn.credit.toLocaleString()}` : '–',
        `KES ${txn.balance.toLocaleString()}`,
        txn.notes || ''
    ]);

    doc.autoTable({
        startY: yPos,
        head: [['Date', 'Type', 'Debit', 'Credit', 'Balance', 'Notes']],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: [0, 87, 61],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            fontSize: 8
        },
        styles: {
            fontSize: 7,
            cellPadding: 2
        },
        columnStyles: {
            0: { cellWidth: 22 },
            1: { cellWidth: 30 },
            2: { halign: 'right', cellWidth: 25 },
            3: { halign: 'right', cellWidth: 25 },
            4: { halign: 'right', cellWidth: 28, fontStyle: 'bold' },
            5: { cellWidth: 'auto', fontSize: 6 }
        }
    });

    yPos = doc.lastAutoTable.finalY + 10;

    // Check if we need a new page for loan summary
    if (yPos > pageHeight - 60) {
        doc.addPage();
        yPos = 20;
    }

    // ===== LOAN SUMMARY (if active loan exists) =====
    if (member.activeLoans > 0) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('ACTIVE LOAN SUMMARY', 14, yPos);
        yPos += 2;

        doc.autoTable({
            startY: yPos,
            head: [['Item', 'Value']],
            body: [
                ['Loan ID', 'LN-045'],
                ['Loan Amount', `KES ${member.activeLoans.toLocaleString()}`],
                ['Monthly Installment', 'KES 2,500'],
                ['Loan Period', '25 months'],
                ['Paid Installments', '12'],
                ['Remaining Installments', '13'],
                ['Outstanding Balance', `KES ${member.activeLoans.toLocaleString()}`],
                [{
                    content: 'Status',
                    styles: { fontStyle: 'bold' }
                }, {
                    content: 'ACTIVE',
                    styles: {
                        fontStyle: 'bold',
                        textColor: [0, 128, 0]
                    }
                }]
            ],
            theme: 'grid',
            headStyles: { fillColor: [0, 87, 61], textColor: [255, 255, 255], fontStyle: 'bold' },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 80 },
                1: { halign: 'right' }
            }
        });

        yPos = doc.lastAutoTable.finalY + 10;
    }

    // ===== FOOTER =====
    // Add footer to all pages
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        // Footer line
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.5);
        doc.line(14, pageHeight - 25, pageWidth - 14, pageHeight - 25);

        // Footer text
        doc.setFontSize(7);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 100, 100);
        doc.text(
            'This statement is system-generated by UKOMBOZI Table Banking System and reflects transactions',
            pageWidth / 2,
            pageHeight - 20,
            { align: 'center' }
        );
        doc.text(
            'recorded during official group meetings and repayments. All figures are auto-calculated and auditable.',
            pageWidth / 2,
            pageHeight - 15,
            { align: 'center' }
        );

        // Page number
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(
            `Page ${i} of ${pageCount}`,
            pageWidth - 14,
            pageHeight - 10,
            { align: 'right' }
        );
    }

    // Generate filename
    const filename = `${member.name.replace(/\s+/g, '_')}_Statement_${new Date().toISOString().split('T')[0]}.pdf`;

    // Save the PDF
    doc.save(filename);

    return filename;
};

/**
 * Generate PDF for member ledger export
 */
export const generateLedgerPDF = (member, transactions) => {
    return generateMemberStatementPDF(member, transactions, 'All Time');
};

/**
 * Generate PDF for specific period
 */
export const generatePeriodStatementPDF = (member, transactions, startDate, endDate) => {
    const period = `${startDate} to ${endDate}`;
    return generateMemberStatementPDF(member, transactions, period);
};
